<?php
// GENERATED FROM schemas/ — do not edit manually.
declare(strict_types=1);
namespace Lcp;
final readonly class MessageModel { public function __construct(public string $id, public string $type, public string $timestamp, public string $senderId, public string $receiverId, public ?string $correlationId, public string $idempotencyKey, public bool $test = false, public array $security = []) {} }
final readonly class EnvelopeModel { public function __construct(public string $version, public MessageModel $message, public mixed $payload) {} }
final readonly class LeadPayload { public function __construct(public string $leadId, public string $status, public string $channel, public array $consumer, public array $location, public array $attributes, public ?string $externalId = null, public ?string $submittedAt = null, public array $compliance = [], public array $provenance = [], public array $exclusivity = [], public array $contactWindow = [], public array $leadQuality = [], public array $expiry = []) {} }
final readonly class CallPayload { public function __construct(public string $leadId, public string $status, public string $channel, public array $consumer, public array $location, public array $call, public ?string $externalId = null, public ?string $submittedAt = null, public array $compliance = [], public array $provenance = [], public array $attributes = [], public array $expiry = [], public array $exclusivity = []) {} }
final readonly class PingPayload { public function __construct(public string $pingId, public string $leadReference, public string $phoneHash, public string $countryCode, public string $vertical, public int $floorPriceCents, public string $currency, public ?string $publisherId = null, public ?string $offerId = null, public ?string $emailHash = null, public array $attributes = []) {} }
final readonly class PostPayload { public function __construct(public string $leadId, public string $deliveredAt, public int $priceCents, public string $currency, public string $buyerId, public array $consumer, public array $location, public array $attributes, public ?string $submittedAt = null, public ?string $offerId = null, public ?string $buyerReference = null, public array $pricing = [], public array $compliance = [], public array $provenance = []) {} }
final readonly class BidPayload { public function __construct(public string $pingId, public string $decision, public int $bidPriceCents, public string $currency, public ?int $estimatedContactSeconds = null, public ?string $buyerReference = null, public ?string $rejectReason = null, public ?int $capacityRemaining = null) {} }
final readonly class AckPayload { public function __construct(public string $originalMessageId, public string $status, public array $errors = [], public ?string $leadId = null, public ?string $requestId = null, public ?string $rejectionReason = null) {} }
final readonly class EventPayload { public function __construct(public string $leadId, public string $event, public string $timestamp, public array $details = [], public ?string $externalReference = null) {} }
final readonly class OfferModel { public function __construct(public string $offerId, public string $buyerId, public string $vertical, public array $countries, public int $floorPriceCents, public string $currency, public ?string $tenantId = null, public bool $active = true, public ?string $routingMode = null, public ?string $schemaVersion = null, public array $extensions = []) {} }
