// GENERATED FROM schemas/ — do not edit manually.
package com.spearsystems.lcp

data class MessageModel(val id: String, val type: String, val timestamp: String, val senderId: String, val receiverId: String, val correlationId: String?, val idempotencyKey: String, val test: Boolean = false, val security: Any? = null)
data class EnvelopeModel(val version: String, val message: MessageModel, val payload: Any?)
data class LeadPayload(val leadId: String, val status: String, val channel: String, val consumer: Any, val location: Any, val attributes: Map<String, Any?>, val externalId: String? = null, val submittedAt: String? = null, val compliance: Any? = null, val provenance: Any? = null, val exclusivity: Any? = null, val contactWindow: Any? = null, val leadQuality: Any? = null, val expiry: Any? = null, val attachments: List<Map<String, Any?>>? = null)
data class CallPayload(val leadId: String, val status: String, val channel: String, val consumer: Any, val location: Any, val call: Any, val externalId: String? = null, val submittedAt: String? = null, val compliance: Any? = null, val provenance: Any? = null, val attributes: Any? = null, val expiry: Any? = null, val exclusivity: Any? = null, val attachments: List<Map<String, Any?>>? = null)
data class PingPayload(val pingId: String, val leadReference: String, val phoneHash: String, val countryCode: String, val vertical: String, val floorPriceCents: Long, val currency: String, val publisherId: String? = null, val offerId: String? = null, val emailHash: String? = null, val attributes: Map<String, Any?> = emptyMap())
data class PostPayload(val leadId: String, val deliveredAt: String, val priceCents: Int, val currency: String, val buyerId: String, val consumer: Any, val location: Any, val attributes: Map<String, Any?>, val submittedAt: String? = null, val offerId: String? = null, val buyerReference: String? = null, val pricing: Any? = null, val compliance: Any? = null, val provenance: Any? = null, val call: Any? = null, val attachments: List<Map<String, Any?>>? = null)
data class BidPayload(val pingId: String, val decision: String, val bidPriceCents: Long, val currency: String, val estimatedContactSeconds: Long? = null, val buyerReference: String? = null, val rejectReason: String? = null, val capacityRemaining: Long? = null)
data class AckPayload(val originalMessageId: String, val status: String, val errors: List<Any>? = null, val leadId: String? = null, val requestId: String? = null, val rejectionReason: String? = null)
data class EventPayload(val leadId: String, val event: String, val timestamp: String, val details: Map<String, Any?>? = null, val externalReference: String? = null)
data class OfferModel(val offerId: String, val buyerId: String, val vertical: String, val countries: List<String>, val floorPriceCents: Int, val currency: String, val tenantId: String? = null, val active: Boolean = true, val routingMode: String? = null, val schemaVersion: String? = null, val extensions: Map<String, Any?>? = null, val allowedPublisherIds: List<String>? = null, val allowedBrandIds: List<String>? = null, val attributeEquals: Map<String, Any?>? = null, val attributeIn: Map<String, Any?>? = null, val monthlyMinimumPayable: Int? = null, val monthlyMaximumPayable: Int? = null, val monthlyQuotaTimezone: String? = null, val monthlyQuotaPolicy: String? = null, val payableRules: Map<String, Any?>? = null, val callRoutingMode: String? = null, val connectTimeoutSeconds: Int? = null)
