import unittest
from pathlib import Path
from tempfile import TemporaryDirectory
from unittest.mock import patch

from tools.check_commit_attribution import (
    check_range,
    find_violations,
    load_policy_config,
    normalize_message_file,
    strip_attributions,
)


class CommitAttributionPolicyTests(unittest.TestCase):
    def test_generated_attribution_is_rejected(self) -> None:
        violations = find_violations("Change behavior\n\n🤖 Generated with an automation tool")

        self.assertEqual(len(violations), 1)
        self.assertEqual(violations[0][1], "generated attribution")

    def test_coauthor_trailer_is_rejected_case_insensitively(self) -> None:
        violations = find_violations(
            "Document release\n\nco-authored-by: Codebuff <NOREPLY@CODEBUFF.COM>"
        )

        self.assertEqual(len(violations), 1)
        self.assertEqual(violations[0][1], "generated co-author attribution")

    def test_human_coauthor_trailer_is_preserved(self) -> None:
        self.assertEqual(
            find_violations(
                "Document release\n\nCo-Authored-By: Example <example@example.com>"
            ),
            [],
        )

    def test_generated_coauthor_identities_are_configurable(self) -> None:
        with TemporaryDirectory() as directory:
            policy_file = Path(directory) / "attribution-policy.json"
            policy_file.write_text(
                '{"generated_coauthor_names": ["buildbot"], '
                '"generated_coauthor_emails": ["bot@example.test"]}',
                encoding="utf-8",
            )

            identities = load_policy_config(policy_file)

            self.assertEqual(
                find_violations(
                    "Document release\n\nCo-Authored-By: BuildBot <bot@example.test>",
                    identities,
                )[0][1],
                "generated co-author attribution",
            )
            self.assertEqual(
                find_violations(
                    "Document release\n\nCo-Authored-By: Codebuff <noreply@codebuff.com>",
                    identities,
                ),
                [],
            )

    @patch(
        "tools.check_commit_attribution._commit_messages",
        return_value=[("abc123", "Change behavior\n\nGenerated by a tool")],
    )
    def test_check_range_reports_commit_sha(self, _commit_messages) -> None:
        self.assertEqual(
            check_range("base", "head"),
            ["abc123: line 3: generated attribution: Generated by a tool"],
        )

    def test_strip_attributions_removes_only_prohibited_lines(self) -> None:
        message = (
            "Document release\n"
            "Generated by a tool\n"
            "Reviewed-by the maintainer.\n"
            "Co-Authored-By: Example <example@example.com>\n"
            "Co-Authored-By: Codebuff <noreply@codebuff.com>\n"
        )

        self.assertEqual(
            strip_attributions(message),
            "Document release\nReviewed-by the maintainer.\n"
            "Co-Authored-By: Example <example@example.com>\n",
        )

    def test_normalize_message_file_updates_file_in_place(self) -> None:
        with TemporaryDirectory() as directory:
            message_file = Path(directory) / "COMMIT_EDITMSG"
            message_file.write_text(
                "Document release\n\nGenerated with an automation tool\n",
                encoding="utf-8",
            )

            violations = normalize_message_file(message_file)

            self.assertEqual(len(violations), 1)
            self.assertEqual(
                message_file.read_text(encoding="utf-8"),
                "Document release\n\n",
            )

    def test_signed_off_by_is_not_an_attribution_trailer(self) -> None:
        self.assertEqual(
            find_violations(
                "Fix typo\n\nSigned-off-by: Randy Beno <randy.riad@gmail.com>"
            ),
            [],
        )

    def test_normal_commit_message_is_allowed(self) -> None:
        self.assertEqual(
            find_violations("Document the v1.0.0 release\n\nReviewed-by the maintainer."),
            [],
        )


if __name__ == "__main__":
    unittest.main()
