// GENERATED FROM schemas/ — do not edit manually.
import Foundation

public struct LCPMessageModel: Codable { public let id: String; public let type: String; public let timestamp: String; public let senderId: String; public let receiverId: String; public let correlationId: String?; public let idempotencyKey: String; public let test: Bool; public init(id: String, type: String, timestamp: String, senderId: String, receiverId: String, correlationId: String?, idempotencyKey: String, test: Bool = false) { self.id = id; self.type = type; self.timestamp = timestamp; self.senderId = senderId; self.receiverId = receiverId; self.correlationId = correlationId; self.idempotencyKey = idempotencyKey; self.test = test } }
public struct LCPEnvelopeModel: Codable { public let version: String; public let message: LCPMessageModel; public let payload: JSONValue }
public struct LCPLeadPayload: Codable { public let leadId: String; public let status: String; public let channel: String; public let consumer: [String: JSONValue]; public let location: [String: JSONValue]; public let attributes: [String: JSONValue]; public let externalId: String?; public let submittedAt: String?; public let compliance: [String: JSONValue]?; public let provenance: [String: JSONValue]?; public let attachments: [[String: JSONValue]]? }
public struct LCPCallPayload: Codable { public let leadId: String; public let status: String; public let channel: String; public let consumer: [String: JSONValue]; public let location: [String: JSONValue]; public let call: [String: JSONValue]; public let externalId: String?; public let submittedAt: String?; public let attachments: [[String: JSONValue]]? }
public struct LCPPingPayload: Codable { public let pingId: String; public let leadReference: String; public let phoneHash: String; public let countryCode: String; public let vertical: String; public let floorPriceCents: Int; public let currency: String; public let publisherId: String?; public let offerId: String?; public let emailHash: String?; public let attributes: [String: JSONValue]? }
public struct LCPPostPayload: Codable { public let leadId: String; public let deliveredAt: String; public let priceCents: Int; public let currency: String; public let buyerId: String; public let consumer: [String: JSONValue]; public let location: [String: JSONValue]; public let attributes: [String: JSONValue]; public let call: [String: JSONValue]?; public let attachments: [[String: JSONValue]]? }
public struct LCPBidPayload: Codable { public let pingId: String; public let decision: String; public let bidPriceCents: Int; public let currency: String; public let estimatedContactSeconds: Int?; public let buyerReference: String?; public let rejectReason: String?; public let capacityRemaining: Int? }
public struct LCPAckPayload: Codable { public let originalMessageId: String; public let status: String; public let errors: [JSONValue]?; public let leadId: String?; public let requestId: String?; public let rejectionReason: String? }
public struct LCPEventPayload: Codable { public let leadId: String; public let event: String; public let timestamp: String; public let details: [String: JSONValue]?; public let externalReference: String? }
public struct LCPOfferModel: Codable { public let offerId: String; public let buyerId: String; public let vertical: String; public let countries: [String]; public let floorPriceCents: Int; public let currency: String; public let tenantId: String?; public let active: Bool; public let routingMode: String?; public let schemaVersion: String?; public let extensions: [String: JSONValue]? }

public enum JSONValue: Codable { case string(String), number(Double), bool(Bool), object([String: JSONValue]), array([JSONValue]), null
    public init(from decoder: Decoder) throws { let container = try decoder.singleValueContainer(); if container.decodeNil() { self = .null } else if let value = try? container.decode(Bool.self) { self = .bool(value) } else if let value = try? container.decode(Double.self) { self = .number(value) } else if let value = try? container.decode(String.self) { self = .string(value) } else if let value = try? container.decode([String: JSONValue].self) { self = .object(value) } else { self = .array(try container.decode([JSONValue].self)) } }
    public func encode(to encoder: Encoder) throws { var container = encoder.singleValueContainer(); switch self { case .string(let value): try container.encode(value); case .number(let value): try container.encode(value); case .bool(let value): try container.encode(value); case .object(let value): try container.encode(value); case .array(let value): try container.encode(value); case .null: try container.encodeNil() } }
}
